# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: actions/checkout@v2
    - name: Run yarn install
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: Run Unit Tests
    - run: vue-cli-service test:unit --ui=bdd tests/unit --recursive
      env:
        NODE_ENV: test
